apiVersion: v1
kind: Service
metadata:
  name: fib-service
  labels:
    run: fib
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: fib
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib
spec:
  selector:
    matchLabels:
      run: fib
  template:
    metadata:
      labels:
        run: fib
    spec:
      containers:
      - name: fib
        image: knusperkrone/fib
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "756Mi"
            cpu: "450m"
        