apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fib
spec:
  scaleTargetRef:
    kind: Deployment
    name: fib
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
