apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fib-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fib-service
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
