fullname: "ingress-live-demo" 

image:
  name: "knusperkrone/live-demo-frontend"
  tag: "base"

ingress:
  enabled: true 
  className: "nginx"
  annotations: 
    kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: live-demo.bu8.io
      paths:
        - path: /api/fib/(.*)
          pathType: Prefix
          service: fib-service
          port: 8080
        - path: /(.*)
          pathType: Prefix
          service: frontend-service
          port: 80
  tls: 
    - secretName: chart-example-tls
      hosts:
        - live-demo.bu8.io
